spring:
  cloud:
    gateway:
      routes:
        - id: microservices-users
          uri: ${USER_URL:http://host.docker.internal:8001}
          predicates:
            - Path=/api/v1/usuarios/**
          filters:
            - AuthenticationFilter


        - id: microservices-accounts
          uri: ${ACCOUNT_URL:http://host.docker.internal:8002}
          predicates:
            - Path=/api/v1/cuentas/**
          filters:
            - AuthenticationFilter


        - id: microservices-transactions
          uri: ${TRANSACTION_URL:http://host.docker.internal:8003}
          predicates:
            - Path=/api/v1/transacciones/**
          filters:
            - AuthenticationFilter


        - id: microservices-auth
          uri: ${AUTH_URL:http://host.docker.internal:9000}
          predicates:
            - Path=/api/v1/auth/**



